apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - orchestrator-deploy.yaml
  - tool-exec-deploy.yaml
  - ui-deploy.yaml
  - tools-core-deploy.yaml
  - py2-runner-deploy.yaml
  - py3-runner-deploy.yaml
  - qdrant-statefulset.yaml
  - ollama-deploy.yaml
