apiVersion: apps/v1
kind: Deployment
metadata:
  name: aicl-py2-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aicl-py2-runner
  template:
    metadata:
      labels:
        app: aicl-py2-runner
    spec:
      containers:
        - name: py2-runner
          image: aicl-py2-runner:latest
          imagePullPolicy: IfNotPresent
          command: ["bash", "-lc", "tail -f /dev/null"]
